export const listaDeIcones = {
  close: "si:close-fill",
  home: "proicons:home",
  categoria: "mdi:category-plus-outline",
  produto: "fluent-mdl2:product-variant",
  lojaParceia: "mdi:store-check-outline",
  flechaDireita: "pepicons-print:arrow-right",
  whatsApp: "mdi:whatsapp",
  instagram: "mdi:instagram",
  facebook: "mdi:facebook",
  carrinho: "lineicons:cart-2",
  etiqueta: "entypo:price-tag",
  avatar: "stash:user-avatar-light",
  filtro: "mynaui:filter-solid",
  senha: "mdi:password-outline",
  sair: "material-symbols-light:logout-rounded",
  pedido: "lsicon:order-outline",
  lixeira: "material-symbols-light:delete-outline",
  searchGlobal: "streamline-ultimate:network-search",
  loading: "eos-icons:bubble-loading",
  download: "material-symbols-light:download",
};
