
name: Docker Image CI

on:
  push:
    branches: ["real-jigs"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Make envfile
        run: |
          cat > .env.production
          echo "NEXT_PUBLIC_URL_API=${{ secrets.URL_API }}" >> .env.production
          echo "NEXT_PUBLIC_PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> .env.production
          echo "$(<.env.production)"
      - name: Build
        run: docker build . -t brunobentocaina/real-jigs-ui:v0.1.0
      - name: Push
        run: |
          docker login -u brunobentocaina -p ${{ secrets.DOCKER_HUB_KEY }}
          docker push brunobentocaina/real-jigs-ui:v0.1.0
